# Generated by Django 4.2.1 on 2023-05-24 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('feedback_name', models.CharField(max_length=7)),
                ('feedback_email', models.EmailField(max_length=254)),
                ('feedback_content', models.TextField(max_length=50)),
                ('feedback_password', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='영어 소문자와 숫자만 사용할 수 있습니다.', regex='^[a-z0-9]+$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
