# Generated by Django 4.2.1 on 2023-05-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedbackuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
