# Generated by Django 4.2.1 on 2023-05-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feedbackuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackuser',
            name='feedback_password',
            field=models.CharField(max_length=10),
        ),
    ]
